/****************************************************************************
*   Generated by ACUITY 5.0.0
*   Match ovxlib 1.0.12
*
*   Neural Network application project entry file
****************************************************************************/
/*-------------------------------------------
                Includes
-------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef __linux__
#include <time.h>
#elif defined(_WIN32)
#include <windows.h>
#endif

#define _BASETSD_H

#include "vsi_nn_pub.h"

#include "vnn_global.h"
#include "vnn_pre_process.h"
#include "vnn_post_process.h"
#include "vnn_inceptionv3.h"


#include "main.h"
// We have to remove the prefix "static" to use main.c as a .so file.
// static vsi_nn_graph_t *vnn_CreateNeuralNetwork(const char *data_file_name);
// static vsi_status vnn_VerifyGraph(vsi_nn_graph_t *graph);
// static vsi_status vnn_ProcessGraph(vsi_nn_graph_t *graph);
// static void vnn_ReleaseNeuralNetwork(vsi_nn_graph_t *graph );
// static vsi_status vnn_PostProcessNeuralNetwork(vsi_nn_graph_t *graph);

/*-------------------------------------------
                  Main Functions
-------------------------------------------*/
int main
    (
    int argc,
    char **argv
    )
{
    vsi_status status = VSI_FAILURE;
    vsi_nn_graph_t *graph;
    const char *data_name = NULL;

    if(argc < 3)
    {
        printf("Usage: %s data_file inputs...\n", argv[0]);
        return -1;
    }

    data_name = (const char *)argv[1];

    /* Create the neural network */
    graph = vnn_CreateNeuralNetwork( data_name );
    //TEST_CHECK_PTR(graph, final);

    /* Pre process the image data */
    status = vnn_PreProcessNeuralNetwork( graph, argc, argv );
    //TEST_CHECK_STATUS( status, final );

    /* Verify graph */
    status = vnn_VerifyGraph(graph);
    //TEST_CHECK_STATUS(status, final);

    /* Process graph */
    status = vnn_ProcessGraph( graph );
    //TEST_CHECK_STATUS( status, final );

    if(VNN_APP_DEBUG)
    {
        /* Dump all node outputs */
        vsi_nn_DumpGraphNodeOutputs(graph, "./network_dump", NULL, 0, TRUE, 0);
    }

    /* Post process output data */
    status = vnn_PostProcessNeuralNetwork( graph );
    //TEST_CHECK_STATUS( status, final );

final:
    vnn_ReleaseNeuralNetwork( graph );
    printf ("All tasks are done.\n");
    return status;
}
