/****************************************************************************
*   Generated by ACUITY 5.0.0
*   Match ovxlib 1.0.12
*
*   Neural Network application project entry file
****************************************************************************/
/*-------------------------------------------
                Includes
-------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef __linux__
#include <time.h>
#elif defined(_WIN32)
#include <windows.h>
#endif

#define _BASETSD_H

#include "vsi_nn_pub.h"

//#include "vnn_global.h"
//#include "vnn_pre_process.h"
//#include "vnn_post_process.h"
//#include "vnn_inceptionv3.h"
#define VNN_APP_DEBUG    0


#include "main.h"

// We have to remove the prefix "static" to use main.c as a .so file.
// static vsi_nn_graph_t *vnn_CreateNeuralNetwork(const char *data_file_name);
// static vsi_status vnn_VerifyGraph(vsi_nn_graph_t *graph);
// static vsi_status vnn_ProcessGraph(vsi_nn_graph_t *graph);
// static void vnn_ReleaseNeuralNetwork(vsi_nn_graph_t *graph );
// static vsi_status vnn_PostProcessNeuralNetwork(vsi_nn_graph_t *graph);

#include <dlfcn.h>

void  vivante_api_clean(void){
    dlerror (); /** Clear the existing dllerror message */
}

void  vivante_api_check(void){
    char *error;
    //if (((error = dlerror()) != NULL) && (result_vnn_CreateNeuralNetwork == NULL)) {
    if ((error = dlerror()) != NULL) {
        printf("%s\n", error);
        exit(EXIT_FAILURE);
    }
}

/*-------------------------------------------
                  Main Functions
-------------------------------------------*/
int main
    (
    int argc,
    char **argv
    )
{
    vsi_status status = VSI_FAILURE;
    vsi_nn_graph_t *graph;
    const char *data_name = NULL;

    // dlopen variables
    void* handle;
    const char *lib_name = "./libinceptionv3.so";

    if(argc < 3)
    {
        printf("Usage: %s data_file inputs...\n", argv[0]);
        return -1;
    }

    data_name = (const char *)argv[1];


    /* Create the neural network */
    //graph = vnn_CreateNeuralNetwork( data_name );
    //TEST_CHECK_PTR(graph, final);
    handle = dlopen(lib_name, RTLD_NOW);
    vsi_nn_graph_t * (*result_vnn_CreateNeuralNetwork)(const char *);
    vivante_api_clean();
    result_vnn_CreateNeuralNetwork = dlsym(handle, "vnn_CreateNeuralNetwork");
    vivante_api_check();
    graph = result_vnn_CreateNeuralNetwork(data_name);
    dlclose(handle);

    printf("debug: input-tensor id: %d. \n", graph->input.tensors[0]); 
    printf("debug: output-tensor id: %d. \n", graph->output.tensors[0]); 

    vsi_nn_tensor_t *tensor = NULL;
    tensor = vsi_nn_GetTensor(graph, graph->input.tensors[0]);
    if (tensor == NULL)
      return -1;
    printf ("debug: input tensor(C,W,H,N,fmt,vx_type, type): %d, %d, %d, %d, %d, %d, %d \n", tensor->attr.size[0], tensor->attr.size[1], tensor->attr.size[2], tensor->attr.size[3], tensor->attr.dtype.fmt, tensor->attr.dtype.vx_type, VSI_NN_TYPE_UINT8);

    //vsi_nn_tensor_t *tensor = NULL;
    tensor = vsi_nn_GetTensor(graph, graph->output.tensors[0]);
    if (tensor == NULL)
      return -1;
    printf ("debug: output tensor(C,W,H,N,fmt,vx_type, type): %d, %d, %d, %d, %d, %d, %d \n", tensor->attr.size[0], tensor->attr.size[1], tensor->attr.size[2], tensor->attr.size[3], tensor->attr.dtype.fmt, tensor->attr.dtype.vx_type, VSI_NN_TYPE_FLOAT16);



    /* Pre process the image data */
    //status = vnn_PreProcessNeuralNetwork( graph, argc, argv );
    //TEST_CHECK_STATUS( status, final );

    // Run Pre-process for the image data.
    // Note that this API requires jpeg-9a library (libjpeg-9a.a).
    vsi_status (*result_vnn_PreProcessNeuralNetwork)(vsi_nn_graph_t *, int, char**);
    vivante_api_clean();
    result_vnn_PreProcessNeuralNetwork = dlsym(handle, "vnn_PreProcessNeuralNetwork");
    vivante_api_check();
    status = result_vnn_PreProcessNeuralNetwork(graph, argc, argv);


    /* Verify graph */
    //status = vnn_VerifyGraph(graph);
    //TEST_CHECK_STATUS(status, final);
    handle = dlopen(lib_name, RTLD_NOW);
    vsi_status (*result_vnn_VerifyGraph)(vsi_nn_graph_t *);
    vivante_api_clean();
    result_vnn_VerifyGraph = dlsym(handle, "vnn_VerifyGraph");
    vivante_api_check();
    status = result_vnn_VerifyGraph(graph);
    dlclose(handle);

    /* Process graph */
    //status = vnn_ProcessGraph( graph );
    //TEST_CHECK_STATUS( status, final );
    handle = dlopen(lib_name, RTLD_NOW);
    vsi_status (*result_vnn_ProcessGraph)(vsi_nn_graph_t *);
    vivante_api_clean();
    result_vnn_ProcessGraph = dlsym(handle, "vnn_ProcessGraph");
    vivante_api_check();
    status = result_vnn_ProcessGraph(graph);
    dlclose(handle);


    if(VNN_APP_DEBUG)
    {
        /* Dump all node outputs */
        printf("Saving debug file (e.g., ./network_dump)\n");
        //vsi_nn_DumpGraphNodeOutputs(graph, "./network_dump", NULL, 0, TRUE, 0);
        handle = dlopen(lib_name, RTLD_NOW);
        void (*result_nn_DumpGraphNodeOutputs)(vsi_nn_graph_t *, const char *, uint32_t *, uint32_t, vsi_bool, vsi_nn_dim_fmt_e);
        vivante_api_clean();
        result_nn_DumpGraphNodeOutputs = dlsym(handle, "vsi_nn_DumpGraphNodeOutputs");
        vivante_api_check();
        result_nn_DumpGraphNodeOutputs(graph, "./network_dump", NULL, 0, TRUE, 0);
        dlclose(handle);

    }

    /* Post process output data */
    //status = vnn_PostProcessNeuralNetwork( graph );
    //TEST_CHECK_STATUS( status, final );
    handle = dlopen(lib_name, RTLD_NOW);
    vsi_status (*result_vnn_PostProcessNeuralNetwork)(vsi_nn_graph_t *);
    vivante_api_clean();
    result_vnn_PostProcessNeuralNetwork = dlsym(handle, "vnn_PostProcessNeuralNetwork");
    vivante_api_check();
    status = result_vnn_PostProcessNeuralNetwork(graph);
    dlclose(handle);


//final:
    //vnn_ReleaseNeuralNetwork( graph );
    handle = dlopen(lib_name, RTLD_NOW);
    void (*result_vnn_ReleaseNeuralNetwork)(vsi_nn_graph_t *);
    vivante_api_clean();
    result_vnn_ReleaseNeuralNetwork = dlsym(handle, "vnn_ReleaseNeuralNetwork");
    vivante_api_check();
    result_vnn_ReleaseNeuralNetwork(graph);
    dlclose(handle);

    printf ("All tasks are done.\n");
    return status;
}
